In [2]:
import numpy as np

In [145]:
small_cloud = np.random.normal( 0, 1, size = (10, 3) )
large_cloud = np.random.normal( 0, 1, size = (100000, 3) )

sig_small = np.cov( small_cloud.T )
sig_large = np.cov( large_cloud.T )

det_small = np.linalg.det( sig_small )
det_large = np.linalg.det( sig_large )

print( sig_small )

print( det_small )
print( det_large )

[[ 0.72056989 -0.23467528  0.00502939]
 [-0.23467528  1.50227491 -0.20374472]
 [ 0.00502939 -0.20374472  1.08786309]]
1.0882247255872637
0.9953581316106006
